Add . and / to cword iskeyword
liquidz/vim-iced pull request #327
Opened 2021-03-26 17:39 UTC by bootleq

I usually remove `.` from `iskeyword` to make word-wise movement easier,
however this can break functions like `jump_to_def` because incomplete symbol.

How about adding those characters to `iskeyword` as an safety guard? Avoid affected by user setting.

2021-03-26 21:05 UTC, liquidz commented
@bootleq Thanks for your contribution!

> How about adding those characters to iskeyword as an safety guard? Avoid affected by user setting.

When we add only those characters, it will not work with the same reason if other characters are removed from `iskeyword`.
So it is better for me to have a constant `iskeyword` for `iced#nrepl#var#cword` as follows.
How about you?

```vim
" c.f. https://vim-jp.org/vimdoc-en/options.html#'iskeyword'
"      https://github.com/vim/vim/blob/v8.2.2660/runtime/ftplugin/clojure.vim#L20
"      https://github.com/liquidz/vim-iced/pull/142
let &isk='@,48-57,_,192-255,?,-,*,!,+,/,=,<,>,.,:,$,#,%,&,39'
```

2021-03-27 03:16 UTC, bootleq commented
@liquidz thanks, I've added a commit to use constant `iskeyword`.

I also see Vim has small different default value for `iskeyword` on Win32, but I think it is irrelevant to our case, so just use the value you mentioned.

2021-03-27 07:01 UTC, liquidz requested changes
@bootleq Thanks!

> I also see Vim has small different default value for iskeyword on Win32, but I think it is irrelevant to our case, so just use the value you mentioned.

👍

2021-03-27 15:35 UTC, bootleq commented on autoload/iced/nrepl/var.vim
> +    setlocal iskeyword=@,48-57,_,192-255,?,-,*,!,+,/,=,<,>,.,:,$,#,%,&,'
Sorry I don't get what is the difference, I just tried some exception after `setlocal` and seems `finally` can successfully revert.

2021-03-27 21:33 UTC, liquidz commented on autoload/iced/nrepl/var.vim
> +    setlocal iskeyword=@,48-57,_,192-255,?,-,*,!,+,/,=,<,>,.,:,$,#,%,&,'
@bootleq  Ah, you're right. Thanks.
`setlocal ...` can be reverted by `let &iskeyword = ...` indeed.

But, it is difficult to always remember that `setlocal ...` can be reverted by `let &iskeyword = ...`, and I'd like to be able to know the behavior by reading the code.

`let &iskeyword = ...` makes it clear in the code that it holds the original value([*1](https://github.com/liquidz/vim-iced/blob/3.1.0/autoload/iced/nrepl/var.vim#L5)), temporarily overwrites it([*2](https://github.com/liquidz/vim-iced/blob/3.1.0/autoload/iced/nrepl/var.vim#L7)), and restores it to the original value([*3](https://github.com/liquidz/vim-iced/blob/3.1.0/autoload/iced/nrepl/var.vim#L10)), so it is easier to read without remembering the difference in behavior.

2021-03-28 02:20 UTC, bootleq commented on autoload/iced/nrepl/var.vim
> +    setlocal iskeyword=@,48-57,_,192-255,?,-,*,!,+,/,=,<,>,.,:,$,#,%,&,'
Thanks for nice explanation. I've reverted to `let`.

2021-03-28 20:48 UTC, liquidz approved these changes
@bootleq Thanks!

2021-03-28 20:49 UTC, merged